# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: get Gox
        run: go get github.com/mitchellh/gox
      - name: Build
        run: make gox
      - name: copy static
        run: cp -r static bin/
      - name: linux server
        uses: actions/upload-artifact@v2
        with:
          name: server linux
          path: bin/goatak_server_linux_amd64
      - name: win server
        uses: actions/upload-artifact@v2
        with:
          name: server windows
          path: bin/goatak_server_windows_amd64.exe
      - name: empty config
        run: echo "---" > bin/atak-web.yml
      - name: linux client
        uses: actions/upload-artifact@v2
        with:
          name: web client linux
          path: |
            bin/webclient_linux_amd64
            bin/static
            bin/atak-web.yml
      - name: win client
        uses: actions/upload-artifact@v2
        with:
          name: web client windows
          path: |
            bin/webclient_windows_amd64.exe
            bin/static
            bin/atak-web.yml
